<?php
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function product_specification_get_meta( $value ) {
    global $post;

    $field = get_post_meta( $post->ID, $value, true );
    if ( ! empty( $field ) ) {
        return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
    } else {
        return false;
    }
}

function product_specification_add_meta_box() {
    add_meta_box(
        'product_specification-product-specification',
        __( 'Product Specification', 'product_specification' ),
        'product_specification_html',
        'post',
        'normal',
        'high'
    );
}
add_action( 'add_meta_boxes', 'product_specification_add_meta_box' );

function product_specification_html( $post) {
    wp_nonce_field( '_product_specification_nonce', 'product_specification_nonce' ); ?>

    <style type="text/css">
        p{
            margin: 0 25px 15px 0;
            padding: 0;
            font-size: 14px;
            display: inline-block;
        }

        .metabox-container label{
            display: inline-block;
            width: 100px;
            font-weight: bold;
        }

        .metabox-container input{
            display: inline-block;
            width: 275px;
        }
    </style>

    <div class="metabox-container">
        <p>
            <label for="product_specification_brand"><?php _e( 'Brand', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_brand" id="product_specification_brand" value="<?php echo product_specification_get_meta( 'product_specification_brand' ); ?>">
        </p>

        <p>
            <label for="product_specification_country"><?php _e( 'Country', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_country" id="product_specification_country" value="<?php echo product_specification_get_meta( 'product_specification_country' ); ?>">
        </p>

        <p>
            <label for="product_specification_rpm"><?php _e( 'RPM', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_rpm" id="product_specification_rpm" value="<?php echo product_specification_get_meta( 'product_specification_rpm' ); ?>">
        </p>

        <p>
            <label for="product_specification_size"><?php _e( 'Size', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_size" id="product_specification_size" value="<?php echo product_specification_get_meta( 'product_specification_size' ); ?>">
        </p>

        <p>
            <label for="product_specification_weight"><?php _e( 'Weight', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_weight" id="product_specification_weight" value="<?php echo product_specification_get_meta( 'product_specification_weight' ); ?>">
        </p>

        <p>
            <label for="product_specification_color"><?php _e( 'Color', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_color" id="product_specification_color" value="<?php echo product_specification_get_meta( 'product_specification_color' ); ?>">
        </p>

        <p>
            <label for="product_specification_pressure"><?php _e( 'Pressure', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_pressure" id="product_specification_pressure" value="<?php echo product_specification_get_meta( 'product_specification_pressure' ); ?>">
        </p>

        <p>
            <label for="product_specification_temperature"><?php _e( 'Temperature', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_temperature" id="product_specification_temperature" value="<?php echo product_specification_get_meta( 'product_specification_temperature' ); ?>">
        </p>

        <p>
            <label for="product_specification_force"><?php _e( 'Force', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_force" id="product_specification_force" value="<?php echo product_specification_get_meta( 'product_specification_force' ); ?>">
        </p>

        <p>
            <label for="product_specification_dimension"><?php _e( 'Dimension', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_dimension" id="product_specification_dimension" value="<?php echo product_specification_get_meta( 'product_specification_dimension' ); ?>">
        </p>

        <p>
            <label for="product_specification_power"><?php _e( 'Power', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_power" id="product_specification_power" value="<?php echo product_specification_get_meta( 'product_specification_power' ); ?>">
        </p>

        <p>
            <label for="product_specification_warranty"><?php _e( 'Warranty', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_warranty" id="product_specification_warranty" value="<?php echo product_specification_get_meta( 'product_specification_warranty' ); ?>">
        </p>

        <p>
            <label for="product_specification_price"><?php _e( 'Price', 'product_specification' ); ?></label>
            <input type="text" name="product_specification_price" id="product_specification_price" value="<?php echo product_specification_get_meta( 'product_specification_price' ); ?>">
        </p>

    </div>

<?php
}

function product_specification_save( $post_id ) {
    if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
    if ( ! isset( $_POST['product_specification_nonce'] ) || ! wp_verify_nonce( $_POST['product_specification_nonce'], '_product_specification_nonce' ) ) return;
    if ( ! current_user_can( 'edit_post', $post_id ) ) return;

    if ( isset( $_POST['product_specification_brand'] ) )
        update_post_meta( $post_id, 'product_specification_brand', esc_attr( $_POST['product_specification_brand'] ) );

    if ( isset( $_POST['product_specification_color'] ) )
        update_post_meta( $post_id, 'product_specification_color', esc_attr( $_POST['product_specification_color'] ) );

    if ( isset( $_POST['product_specification_size'] ) )
        update_post_meta( $post_id, 'product_specification_size', esc_attr( $_POST['product_specification_size'] ) );

    if ( isset( $_POST['product_specification_weight'] ) )
        update_post_meta( $post_id, 'product_specification_weight', esc_attr( $_POST['product_specification_weight'] ) );

    if ( isset( $_POST['product_specification_pressure'] ) )
        update_post_meta( $post_id, 'product_specification_pressure', esc_attr( $_POST['product_specification_pressure'] ) );

    if ( isset( $_POST['product_specification_temperature'] ) )
        update_post_meta( $post_id, 'product_specification_temperature', esc_attr( $_POST['product_specification_temperature'] ) );

    if ( isset( $_POST['product_specification_force'] ) )
        update_post_meta( $post_id, 'product_specification_force', esc_attr( $_POST['product_specification_force'] ) );

    if ( isset( $_POST['product_specification_country'] ) )
        update_post_meta( $post_id, 'product_specification_country', esc_attr( $_POST['product_specification_country'] ) );

    if ( isset( $_POST['product_specification_rpm'] ) )
        update_post_meta( $post_id, 'product_specification_rpm', esc_attr( $_POST['product_specification_rpm'] ) );

    if ( isset( $_POST['product_specification_dimension'] ) )
        update_post_meta( $post_id, 'product_specification_dimension', esc_attr( $_POST['product_specification_dimension'] ) );

    if ( isset( $_POST['product_specification_power'] ) )
        update_post_meta( $post_id, 'product_specification_power', esc_attr( $_POST['product_specification_power'] ) );

    if ( isset( $_POST['product_specification_warranty'] ) )
        update_post_meta( $post_id, 'product_specification_warranty', esc_attr( $_POST['product_specification_warranty'] ) );

    if ( isset( $_POST['product_specification_price'] ) )
        update_post_meta( $post_id, 'product_specification_price', esc_attr( $_POST['product_specification_price'] ) );

}
add_action( 'save_post', 'product_specification_save' );

/*
	Usage: product_specification_get_meta( 'product_specification_brand' )
	Usage: product_specification_get_meta( 'product_specification_color' )
	Usage: product_specification_get_meta( 'product_specification_size' )
	Usage: product_specification_get_meta( 'product_specification_weight' )
	Usage: product_specification_get_meta( 'product_specification_pressure' )
	Usage: product_specification_get_meta( 'product_specification_temperature' )
	Usage: product_specification_get_meta( 'product_specification_force' )
	Usage: product_specification_get_meta( 'product_specification_country' )
*/
